all:
  children:
    # --- Proxmox 伺服器群組 ---
    proxmox:
      hosts:
        pve-1:
          ansible_host: pve-1.server.zaidho.me
        pve-2:
          ansible_host: pve-2.server.zaidho.me

    # --- Raspberry Pi 群組 (Ubuntu 24.04) ---
    raspberry_pi:
      hosts:
        mimir:
          ansible_host: mimir.server.zaidho.me
          ansible_user: mimir
        heimdall:
          ansible_host: heimdall.server.zaidho.me
          ansible_user: heimdall
        keymaker:
          ansible_host: keymaker.server.zaidho.me
          ansible_user: keymaker

    pomerium:
      hosts:
        heimdall:
          pomerium_dir: /home/heimdall/pomerium
